version: '3.9'
services:
  client:
    image: sb3-client:latest
    container_name: sb3-client
    build: ./client
    restart: always
    environment:
      - NODE_ENV=development
    expose:
      - '8080'
  api:
    image: sb3-api:latest
    container_name: sb3-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sb3
      - NODE_ENV=development
    restart: always
    volumes:
      - ./api:/sb3-api
    ports:
      - '3001:3001'
  db:
    image: sb3-db:latest
    container_name: sb3-db
    build: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  proxy:
    image: sb3-proxy:latest
    container_name: sb3-proxy
    build: ./proxy
    restart: always
    volumes:
      - ./proxy:/etc/nginx/conf.d
    ports:
      - '80:80'
