version: '3.9'
services:
  client:
    image: kc-client:latest
    container_name: kc-client
    environment:
      - NODE_ENV=production
    restart: always
    expose:
      - '8080'
  api:
    image: kc-api:latest
    container_name: kc-api
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/kc
      - NODE_ENV=production
    restart: always
    expose:
      - '3001'
  db:
    image: kc-db:latest
    container_name: kc-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    expose:
      - '5432'
  proxy:
    image: kc-proxy:latest
    container_name: kc-proxy
    restart: always
    volumes:
      - ./proxy:/etc/nginx/conf.d
    ports:
      - '80:80'
