version: '3.9'
services:
  reverse-proxy:
    image: kc-proxy:latest
    build: ./proxy
  api:
    image: kc-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
  client:
    image: kc-client:latest
    build: ./client
    environment:
      - NODE_ENV=production
  db:
    image: kc-db:latest
    build: ./database
