version: '3.9'
services:
  reverse-proxy:
    image: sb3-proxy:latest
    build: ./proxy
  api:
    image: sb3-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
  client:
    image: sb3-client:latest
    build: ./client
    environment:
      - NODE_ENV=production
  db:
    image: sb3-db:latest
    build: ./database
