FROM node:14.16.0-alpine

WORKDIR /kc-api

COPY prisma/ wait-for-it.sh package.json ./

RUN apk update &&\
    apk add bash &&\
    chmod 755 wait-for-it.sh &&\
    npm install -g pnpm &&\
    pnpm install

COPY . ./

ENV HOST=0.0.0.0 PORT=3001

CMD ["./wait-for-it.sh", "db:5432", "--strict", "--timeout=300", "--", "pnpm", "start:dev"]
